services:
  - type: web
    name: booking-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn booking_agent:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000 